// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns aggregated usage and subscription metrics. Admin role required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get system metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique nonce",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "System metrics",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_admin_controller.metricsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all registered users ordered by creation date. Admin role required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique nonce",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/role": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Promotes or demotes a user to/from admin. Role must be \"user\" or \"admin\". Admin role required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Set user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp (seconds since epoch, e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request (e.g. uuid or random hex)",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target user UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role assignment payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_controller.setRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Invalid role or user ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/usage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns detailed usage stats for a specific user: free quota used this month, total messages, and all subscription bundles. Admin role required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get user usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique nonce",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User usage details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_admin_controller.userUsageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/chat/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of the authenticated user's chat history, newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "List chat messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page, 1–100 (default: 20)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated messages",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_chat_controller.messageResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits a question, validates quota (free tier or subscription bundle), calls the mocked AI, stores and returns the result. Deducts from the subscription bundle with the most recent remaining quota.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Send a message to the AI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567) — must be within ±5 min of server time",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID (rejected if reused — anti-replay)",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Question payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_chat_dto.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message stored and AI response returned",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_chat_controller.messageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "402": {
                        "description": "No quota available — subscribe to continue",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/chat/messages/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns one chat message by ID. Users can only retrieve their own messages.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get a single chat message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message UUID (e.g. 550e8400-e29b-41d4-a716-446655440000)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chat message",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_chat_controller.messageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all subscription bundles (active and inactive) for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "List subscriptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of subscriptions",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_subscription_controller.subscriptionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new active subscription for the user. Users may hold multiple active bundles simultaneously. Quota is deducted from the newest bundle that still has capacity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Create a subscription bundle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Subscription details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_subscription_dto.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Subscription created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_subscription_controller.subscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Validation error — see details for field messages",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single subscription bundle by ID. Users can only access their own subscriptions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Get a subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subscription UUID (e.g. a1b2c3d4-e5f6-7890-abcd-ef1234567890)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_subscription_controller.subscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/{id}/auto-renew": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enables or disables automatic renewal for a subscription. Cannot be re-enabled on a cancelled subscription.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Toggle auto-renew",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subscription UUID (e.g. a1b2c3d4-e5f6-7890-abcd-ef1234567890)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Set enable to true to turn on auto-renew, false to turn it off",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_subscription_dto.ToggleAutoRenewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated subscription",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_subscription_controller.subscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or subscription is cancelled",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/api/v1/subscriptions/{id}/cancel": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks the subscription as cancelled. Access is preserved until the end of the billing cycle. Auto-renew is disabled. Historical usage data is preserved.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Cancel a subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix timestamp in seconds (e.g. 1711234567)",
                        "name": "X-Request-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique string per request, e.g. a UUID",
                        "name": "X-Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subscription UUID (e.g. a1b2c3d4-e5f6-7890-abcd-ef1234567890)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cancelled subscription",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_subscription_controller.subscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Already cancelled or invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 OK with subsystem status when healthy, 503 when degraded. Used by load balancers and monitoring systems. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "All systems healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "One or more subsystems degraded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Ammar022_muhammad-ammar-azam_internal_chat_dto.SendMessageRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "description": "Question is the user's prompt.  Required, 1–4000 characters.\nThe validator rejects blank strings and anything exceeding the limit.",
                    "type": "string",
                    "maxLength": 4000,
                    "minLength": 1,
                    "example": "What is quantum computing and how does it work?"
                }
            }
        },
        "github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.ErrorBody"
                },
                "meta": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ammar022_muhammad-ammar-azam_internal_shared_response.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "description": "optional field-level errors"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Ammar022_muhammad-ammar-azam_internal_subscription_dto.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "billing_cycle",
                "tier"
            ],
            "properties": {
                "auto_renew": {
                    "description": "AutoRenew controls whether the subscription automatically renews at the end of the billing cycle.",
                    "type": "boolean",
                    "example": true
                },
                "billing_cycle": {
                    "description": "BillingCycle must be one of: \"monthly\", \"yearly\"\nYearly billing applies a 20% discount on the monthly price.",
                    "type": "string",
                    "enum": [
                        "monthly",
                        "yearly"
                    ],
                    "example": "monthly"
                },
                "tier": {
                    "description": "Tier must be one of: \"basic\", \"pro\", \"enterprise\"\nbasic = 10 msgs | pro = 100 msgs | enterprise = unlimited",
                    "type": "string",
                    "enum": [
                        "basic",
                        "pro",
                        "enterprise"
                    ],
                    "example": "pro"
                }
            }
        },
        "github_com_Ammar022_muhammad-ammar-azam_internal_subscription_dto.ToggleAutoRenewRequest": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "Enable sets auto_renew to true or false.",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_admin_controller.metricsResponse": {
            "type": "object",
            "properties": {
                "active_subscriptions": {
                    "type": "integer"
                },
                "free_quota_usage_this_month": {
                    "type": "integer"
                },
                "generated_at": {
                    "type": "string"
                },
                "messages_today": {
                    "type": "integer"
                },
                "subscriptions_by_tier": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "total_messages": {
                    "type": "integer"
                },
                "total_subscriptions": {
                    "type": "integer"
                },
                "total_users": {
                    "type": "integer"
                }
            }
        },
        "internal_admin_controller.subUsageSummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_messages": {
                    "type": "integer"
                },
                "messages_used": {
                    "type": "integer"
                },
                "tier": {
                    "type": "string"
                }
            }
        },
        "internal_admin_controller.userUsageResponse": {
            "type": "object",
            "properties": {
                "free_messages_used": {
                    "type": "integer"
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_admin_controller.subUsageSummary"
                    }
                },
                "total_messages": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_auth_controller.setRoleRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "description": "Role must be \"user\" or \"admin\".",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ],
                    "example": "admin"
                }
            }
        },
        "internal_chat_controller.messageResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "This is a simulated AI response to your question."
                },
                "completion_tokens": {
                    "type": "integer",
                    "example": 85
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-03-21T10:30:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "prompt_tokens": {
                    "type": "integer",
                    "example": 12
                },
                "question": {
                    "type": "string",
                    "example": "What is quantum computing and how does it work?"
                },
                "response_time_ms": {
                    "type": "integer",
                    "example": 743
                },
                "subscription_id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "total_tokens": {
                    "type": "integer",
                    "example": 97
                }
            }
        },
        "internal_subscription_controller.subscriptionResponse": {
            "type": "object",
            "properties": {
                "auto_renew": {
                    "type": "boolean",
                    "example": true
                },
                "billing_cycle": {
                    "type": "string",
                    "enum": [
                        "monthly",
                        "yearly"
                    ],
                    "example": "monthly"
                },
                "cancelled_at": {
                    "type": "string",
                    "example": "2024-03-15T08:00:00Z"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-03-01T00:00:00Z"
                },
                "end_date": {
                    "type": "string",
                    "example": "2024-04-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "max_messages": {
                    "type": "integer",
                    "example": 100
                },
                "messages_used": {
                    "type": "integer",
                    "example": 23
                },
                "price": {
                    "type": "number",
                    "example": 49.99
                },
                "remaining_messages": {
                    "type": "integer",
                    "example": 77
                },
                "renewal_date": {
                    "type": "string",
                    "example": "2024-04-01T00:00:00Z"
                },
                "start_date": {
                    "type": "string",
                    "example": "2024-03-01T00:00:00Z"
                },
                "tier": {
                    "type": "string",
                    "enum": [
                        "basic",
                        "pro",
                        "enterprise"
                    ],
                    "example": "pro"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Auth0 JWT — prefix with \"Bearer \". Obtain via Auth0 dashboard (APIs → Test tab) or your Auth0 login flow.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Secure AI Chat Backend",
	Description:      "Production-grade AI chat backend with Auth0 authentication, DDD, quota management, and subscription bundles.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
